export type LitTargetKind =
	| "memberFunctionElement"
	| "functionElement"
	| "constructorImplementationElement"
	| "variableElement"
	| "classElement"
	| "interfaceElement"
	| "moduleElement"
	| "memberVariableElement"
	| "constElement"
	| "enumElement"
	| "keyword"
	| "constElement"
	| "alias"
	| "moduleElement"
	| "member"
	| "label"
	| "unknown";
